### ISSUE TITLE
How to reference a nuget package for the designer

### ISSUE THREAD

**Issue by sebmizfsa** [microsoft/winforms-designer-extensibility#10]
Hi,

I try to add the System.Text.Json inside the package because I need it for my editor.
The package is added to the protocol library in the net4.7.2 version.

I added the following line in the package project file

		<_File Include="$(ProjectDir)..\Vitesse.Devices.Core.Protocol\bin\$(Configuration)\net472\System.Text.Json.dll" TargetDir="Design/WinForms" />

If I look inside the nuget package, the file is present at the right place.

But when I Install the package in a client winform app, I have the following error : (a task has been cancelled)
![image](https://user-images.githubusercontent.com/99221794/208470988-39205fc3-4381-44bf-9528-f380c1d912f4.png)

How do I reference a nuget package to be used in the designer by my dialog ?

If I copy directly the file system.text.json.dll in the design/winforms folder, all works well.

Thanks for helping

**Comment by kirsan31** [comment]
Due to error, your problem has nothing to do with the designer, we need to look at the nuget log and / or the package itself.
