### ISSUE TITLE
Simple Test Form does not work

### ISSUE THREAD

**Issue by alprinias** [microsoft/winforms-designer-extensibility#18]
Hi,
following the blog post https://devblogs.microsoft.com/dotnet/winforms-cross-platform-dotnet-maui-command-binding
I downloaded the MauiEidt solution and tried the SimpleTestForm in the MauiEdit.WinForms project (by uncommenting the lines 
        Application.Run(new SimpleTestForm());
        return;
in the Main method of the Program.cs file). The program runs, the form shows up, but nothing happens when I check/uncheck the chackbox, which is supposed the toggle the command availability. I.e. the button never gets enabled and when I set breakpoints in the SampleCommandAvailability property setter (of the SimpleCommandViewModel), they are never hit. (edit: They are only hit after I stop debugging.)

Any idea what might be wrong?

Don't know whether this is related, but the all items in the toolbox are greyed out.  (edit: forget about this, after a Visual Studio Repair, toolbox behaves as expected.)

All this with Visual Studio 2022 Community 17.5.4

Thanks and regards,
Alex

**Comment by KlausLoeffelmann** [comment]
Sorry for the oversight, thanks for fixing it!
