### ISSUE TITLE
Custom Component Designer (RootDesigner)  not working with projects targeting > netcoreapp3.1

### ISSUE THREAD

**Issue by valiahmetovv** [microsoft/winforms-designer-extensibility#23]
Environment
Visual Studio Version 17.7.0 Preview 6.0
OS Version WIN 11

Steps to reproduce the problem:

Unzip attached archive 
[CustomComponentDesigner.zip](https://github.com/microsoft/winforms-designer-extensibility/files/12287055/CustomComponentDesigner.zip)
Build solution projects all except Package and TestProjNetCore31
Build Package project - note that a nuget package will appear in folder …\CustomComponentDesigner\Package\bin\Debug
Add nuget package source and point it to the above mentioned folder
Build TestProjNetCore31

Actuall problem:
1.Go to TestProjNet462
2.Find TestObj.cs , right click and choose “View Designer”, you should see a blue screen as illustrated below:
![image](https://github.com/microsoft/winforms-designer-extensibility/assets/141699579/5ab60850-666a-46ef-87e1-14a3c3aa5a51)

Go to TestProjNetCore31
4.Find TestObj.cs , right click and choose “View Designer”, instead of designer, an error is shown:
![image](https://github.com/microsoft/winforms-designer-extensibility/assets/141699579/8a1e0add-7fa6-46f2-bcec-ad9b7211994b)
Expected: same result as in step 2.

Notes:
Attached solution is an attempt to make custom component designers work using the new out-of-process designer approach.

Take a look at TestObj.cs inside Component project, you will notice that this object is assigned with a Designer attribute:
[Designer(“ExtensionExample.TestObjDesigner, ServerDesigner”, typeof(IRootDesigner))]

The designer implementation is just a stub view, which can be found in projects:DesignerNet462 and DesignerNetCore31, both implementations are mostly the same except that they target different .net versions.

Since VS is a net472 process, the TestProjNet462 project loads the custom designer without any issues.

TestProjNetCore31 targets netcore3.1 app, so it uses the Out-of-proc approach when opening custom controls and components.

cc @merriemcgaw  @KlausLoeffelmann 

**Please reply if custom component designers are supported by latest Microsoft.WinForms.Designer.SDK
If yes, then please assist with making attached project work as expected.**

**If not, please let me know if such functionality will be supported in near future**

**Comment by KlausLoeffelmann** [comment]
Hey @valiahmetovv,

let me take a look at it and come back to you.
Principally, Core 3.1 should be working just fine.

**Comment by KlausLoeffelmann** [comment]
Oh, I just saw. This is about custom root designers, not about custom type editors.

We are working on the first iteration of the API for custom root designers, but while you general approach is absolutely correct, you will need a new (Beta) SDK for that. We are aiming for Visual Studio 17.8 Preview 2 for the release of that Beta SDK.

**Comment by valiahmetovv** [comment]
Hi @KlausLoeffelmann.
Thank you for prompt reply, looking forward to Visual Studio 17.8 Preview 2 release.

**Comment by KlausLoeffelmann** [comment]
Slipped to Preview 3, but we're preparing a new Preview SDK shortly.
Closing this for now.

**Comment by valiahmetovv** [comment]
Hello @KlausLoeffelmann,
As i understand Preview 3 should be available soon, so i wanted to clarify if root designers support is going to be included in this release.

**Comment by Bitcosoftware** [comment]
Why was this closed?  This hasn't been addressed and not fixed.
