### ISSUE TITLE
Type Editor Template is not working in V.S. 17.4.3

### ISSUE THREAD

**Issue by kirsan31** [microsoft/winforms-designer-extensibility#8]
`Microsoft.WinForms.Designer.TypeEditorTemplate.1.1.0-prerelease-preview3`

Microsoft Visual Studio Community 2022
Version 17.4.3
VisualStudio.17.Release/17.4.3+33205.214
Microsoft .NET Framework
Version 4.8.09032

No options at all on second page:
![image](https://user-images.githubusercontent.com/17767561/207694502-e92600ec-f46f-4eb2-8981-5cb61bda27c1.png)

Templates from https://github.com/KlausLoeffelmann/NetControlDesigners/tree/Templates not working too. Worked at 17.4.2.

**Comment by KlausLoeffelmann** [comment]
I just tried, and it is working for me in the latest
* public version
* public preview
* internal preview.

Let's try to find out why you're seeing (or not seeing) this on your particular machine.

![image](https://user-images.githubusercontent.com/9663150/213877246-cb4e3be6-e981-4a6e-927f-4ef23e1fa5eb.png)

**Comment by kirsan31** [comment]
17.4.**4** all working well. So let's assume it was a version 17.4.**3** problem.
